# Generated by Django 2.2.5 on 2020-06-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='year',
            field=models.IntegerField(),
        ),
    ]
