# Generated by Django 2.2.5 on 2020-06-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200617_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='manager.Students')),
            ],
        ),
    ]
