# Generated by Django 2.2.5 on 2020-06-17 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_takeattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takeattendance',
            old_name='owner',
            new_name='roll',
        ),
        migrations.AddField(
            model_name='takeattendance',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='takeattendance',
            name='subject',
            field=models.CharField(default=datetime.datetime(2020, 6, 17, 11, 32, 9, 64531, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
