# Generated by Django 2.2.5 on 2020-06-19 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200617_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeattendance',
            name='date_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date(mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='takeattendance',
            name='subject',
            field=models.CharField(choices=[('DBMS', 'database Management'), ('EG', 'Engineering Drawing'), ('WT', 'Web Technology'), ('AJ', 'Advance Java'), ('.NET', 'Dot Net Technology')], default='DBMS', max_length=6),
        ),
        migrations.AlterField(
            model_name='takeattendance',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
